@baseurl = http://localhost:3000
###
GET {{baseurl}}/api

###
# @name signup
POST {{baseurl}}/api/auth/signup
Content-Type: application/json

{
    "name": "name1",
    "email": "name1@example.com",
    "password": "password1"
}

###
# @name login
POST {{baseurl}}/api/auth/login
Content-Type: application/json

{
    "email": "name1@example.com",
    "password": "password1"
}

### 
@token = {{login.response.body.$.data.token}}

###
# @name me
GET {{baseurl}}/api/auth/me
Authorization: {{token}}