@baseurl = http://localhost:3000
###
GET {{baseurl}}/api

###
# @name signup
POST {{baseurl}}/api/auth/signup
Content-Type: application/json

{
    "name": "name2",
    "email": "name2@example.com",
    "password": "password2"
}

###
# @name login
POST {{baseurl}}/api/auth/login
Content-Type: application/json

{
    "email": "name2@example.com",
    "password": "password2"
}

### 
@token = {{login.response.body.$.data.token}}

###
# @name me
GET {{baseurl}}/api/auth/me
Authorization: {{token}}


###
# @name createProduct
POST {{baseurl}}/api/products
Content-Type: application/json
Authorization: {{token}}

{
    "name": "tea",
    "description": "hot and sweet",
    "tags": ["hot", "sweet", "tea"],
    "price" : 120
}

###